apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "annuaire.fullname" . }}-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "annuaire.labels" . | nindent 4 }}
immutable: {{ .Values.configMap.immutable }}
data:
  LOG_LEVEL: {{ .Values.env.LOG_LEVEL | quote }}
  SCENARIO_VALUE: {{ .Values.configMap.scenarioValue | quote }}
