image:
  repository: ghcr.io/louis-guidez/notif
  tag: ""
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: nginx
  host: notif.devhub.local
  path: /

env:
  LOG_LEVEL: info

resources:
  requests:
    cpu: 25m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

securityContext:
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532
  fsGroup: 65532
  seccompProfile:
    type: RuntimeDefault

probes:
  readiness:
    path: /healthz
    initialDelaySeconds: 1
    periodSeconds: 5
  liveness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 10
